### ISSUE TITLE
Not functioning on Windows or on Mac OSX

### ISSUE THREAD

**Issue by AaronNGray** [vanzylv/youtube-downloader-electron#2]
Getting a blank page and no menus on both Windows and Max OSX

**Comment by vanzylv** [comment]
@AaronNGray I'm pretty sure it's the Youtube API key used for search, I had to disable the key packaged with the binaries. I would suggest using your own API key defined [here](https://github.com/vanzylv/youtube-downloader-electron/blob/master/app/config.js)  and recompiling for your platform. I'll look into making this configurable going forward.
